### ISSUE TITLE
valid-whitespace.json5 is invalid

### ISSUE THREAD

**Issue by d-frey** [json5/json5-tests#1]
AFAICT, Form Feed (`\x0c`) is not a valid whitespace character, even in JSON5.

The testcase

    misc/valid-whitespace.json5

should therefore be renamed to

    misc/invalid-whitespace.txt

**Comment by jordanbtucker** [comment]
`\x0c` is the same as `\f`, which is valid whitespace according to [line 42](https://github.com/json5/json5/blob/v0.5.1/lib/json5.js#L42).

**Comment by d-frey** [comment]
The current state of affairs is unpleasant.

There seem to be multiple sources for JSON5:

* The reference implementation
* The Website (json5.org)
* The WIKI (where JSON5WhiteSpace does *not* list FormFeed)
* Some specification which is referencing ECMAScript grammar

They are, in one word, confusing.

If you want JSON5 to be a standard which is taken seriously outside of the ECMAScript community, I think you really need to clean up the above sources and provide a single, consistent, self-contained specification which can be understood without any reference to ECMAScript.

I tried to help with that by providing a ABNF grammar as used by the RFCs, but if you have no interest in this direction, I'd appreciate a direct and explicit statement. I tried to ask you about that at least two times already, but you seem to avoid to answer this question. To me, the answer is important: If you insist on ECMAScript, which is your right to do, I at least know what to expect and what *not* to expect and I can move on and leave JSON5 behind.

**Comment by jordanbtucker** [comment]
I agree with you on the state of affairs. I have updated the Wiki with a statement saying that the grammar page is deprecated and a link to the spec repo.

As for the website, I'm not sure why you take issue with it, other than the fact that it doesn't reference the spec repo or PDF. Can you please elaborate?

The reference implementation definitely needs to be updated to match the spec, which is still in draft form. Granted, the differences are pretty minor at this point. I'd like to make some time to do that, but I haven't had the chance yet. Maybe you could spare some cycles to perform that task?

As for referencing ECMAScript, this is done because JSON5 borrows a lot of grammar productions from ES5. I could take all of those productions and paste them into the JSON5 spec. I didn't want to bloat the spec, but if you think that would make it better, then I'll consider it. You're always welcome to create a PR too.

I do appreciate the ABNF, as I'm sure that will help to create implementations of JSON5 in other languages. As far as I can tell, it looks like it conforms for the most part. But as I pointed out in [another issue](https://github.com/json5/json5/issues/139#issuecomment-277542191), sometimes there are nuances that are difficult for a grammar to satisfy. Beyond that, I'm not sure what you want me to say. You wrote the ABNF, created a PR in the spec repo, and I merged it, and I think it would be a good addition as an appendix in the spec.

As far as what you can expect, the JSON5 spec references the ES5 spec and even includes hyperlinks to the relevant sections in the ES5 spec (when you click on a grammar production that doesn't start with JSON5). As I said, we could pull those productions directly into the spec, and you're welcome to submit a PR for that too.

**Comment by d-frey** [comment]
For the Wiki: If it is deprecated, what purpose does it serve? Why not just remove it. In fact, I don't feel the Wiki as a whole provides any benefit.

For the Website: It contains a link for "identifier", there it says:

> A JavaScript identifier must start with a letter, underscore (_), or dollar sign ($); subsequent characters can also be digits (0-9). Because JavaScript is case sensitive, letters include the characters "A" through "Z" (uppercase) and the characters "a" through "z" (lowercase).
> 
> You can use most of ISO 8859-1 or Unicode letters such as å and ü in identifiers (for more details see this blog post). You can also use the Unicode escape sequences as characters in identifiers.
> 
> Some examples of legal names are Number_hits, temp99, $credit, and _name.

The first paragraph is clear. The examples at the end match. But then what is this middle part? Confusing.

Also, you say that JSON5 is intended to be a subset of ES5. So I still don't know what an identifier in JSON5 actually is.

Next: The Website seems to make a difference between object keys and strings. Strings allowed to be multi-line (with escaped new-lines). What about Object keys? Unclear.

Number can be hexadecimal **integers**, not floating point. (And yes, hexadecimal floating-point format do exist)

It says numbers can include `NaN`, `-NaN`, `Infinity`, `-Infinity`. This is confusing wrt the allowed explicit `+`. Why is `+NaN` not listed? And why is `-NaN` explicitly listed? Is it different from `NaN`?? Confusing.

Moving on to the reference implementation: You pointed me to it above, when I missed the `\f`. At the same time, look at the reference implementation's definition for escapees. I am not a ES developer, I write most of my code in C++. Occasionally Java (not JavaScript) and Python. I can not help you with your reference implementation, I can barely read it. I can guess what it does, but all the subtleties *will* escape me. It is of absolutely no use to me.

For the specification/PDF, you wrote:

> As for referencing ECMAScript, this is done because JSON5 borrows a lot of grammar productions from ES5. I could take all of those productions and paste them into the JSON5 spec. I didn't want to bloat the spec, but if you think that would make it better, then I'll consider it. You're always welcome to create a PR too.

That is exactly why I wrote the ABNF. To **replace** the grammar you have. Not to complement it and to create further inconsistencies. Pasting the ECMAScript rules into your grammar is not only useless, it is also wrong IIUC. You did say that you want to be a subset of ECMAScript, not full ECMAScript, right? This is why you need to be independent.

I also feel that it is important to keep JSON5 relatively simple. Each extension should provide real benefits. Allowing identifiers to be more complicated than C-style identifiers (maybe with an added `$`) seems unnecessary. Same for several whitespace-characters like "form-feed" or a BOM. Is this really something a human wants to write and not just support for broken software that is too dumb to generate proper files?

So for what to expect: Referencing or copying ES5 grammar rules will not solve this. If you do not intend to be independent of ES5 in your definition/specification of JSON5 (other than maybe being a strict subset of ES5), I'm afraid this will always lead to more work and confusion than simply dropping it and writing a self-contained and consistent spec yourself.

**Comment by jordanbtucker** [comment]
I understand that you have a lot of issues with JSON5 and json5.org and apparently Mozilla's definition of a JavaScript identifier. Unfortunately, listing them at us is not really going to get much done. If you would like to improve this project, I recommend submitting PRs with explanations as to why you want to make the change.

It was not clear to me that you intended the ABNF to replace the current grammar, and I do not think you made it clear. The current spec reflects the ECMA style specs of JavaScript and JSON (and C# as well). The desire for Unicode support makes ABNFs more difficult to implement, so I'm not sure if replacing the formal grammar with an ABNF (which I find more difficult to read as it's meant for computers not humans) is the right path to take.

Remember that this is a community project maintained by very few developers in our spare time. If you would like to contribute, we wholeheartedly welcome that.

**Comment by d-frey** [comment]
We (Colin and me) are working on our libraries in our spare time as well, no one is paying us for it and our time is limited. As is the case for a lot of other developers around.

I think the problem with our communication is that we are coming from very different backgrounds. Professionally, I'm used to reading RFC and other standards, and implementing them to the letter. And standards are not intended for the end-user, but for the implementer. You can have a website for the guy who wants to write a config file in JSON5, but that is far different from a real specification. The latter is very technical, but (ideally) also complete and very precise.

Also, we obviously come from very different programming language backgrounds, which is why I tried to push for a programming language-agnostic specification.

I was hoping that all the hints I already gave will trigger more actions on your side to clean up and improve the various JSON5 information (website, wiki, spec/PDF), as I feel it is rather unproductive if I need to "fight" for every little detail explicitly. And I'm afraid we won't make more progress if you expect me to write PRs for everything. In that case it will be far easier for me to simply drop the baggage and write my very own standard for relaxed JSON. I was hoping it could be JSON5, but I am not so sure anymore. Don't get me wrong: JSON5 still gets a lot of things right and I appreciate those, but then again, it is not complete and independent enough for me to be considered a stable foundation for the future.

**Comment by d-frey** [comment]
Also, back to the original issue of `valid-whitespace.json5`: In the very same file, it says:

    // An invalid form feed character (\x0c) has been entered before this comment.

Shouldn't at least the word "invalid" be removed? Otherwise it is really confusing as I don't understand what "invalid" refers to.
